database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/testSchema
  user: root
  password: sharad
  maxWaitForConnection: 10s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 5 minute
  checkConnectionOnBorrow: true